GET http://localhost:5068/games
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IlVzdWFyaW8iLCJzdWIiOiJVc3VhcmlvIiwianRpIjoiOGZkYTE1NjIiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDoxMzI2NCIsImh0dHBzOi8vbG9jYWxob3N0OjQ0MzQ5IiwiaHR0cDovL2xvY2FsaG9zdDo1MDY4IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI5MSJdLCJuYmYiOjE3MTQzMjQ4NDgsImV4cCI6MTcyMjE4NzI0OCwiaWF0IjoxNzE0MzI0ODUwLCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.tIDUTZ-LZZGjLzBUB1M32qz-jguJOmkXEpvfo_g76i8

###
GET http://localhost:5068/games/5

###
POST http://localhost:5068/games
Content-Type: application/json

{
    "name":"Minecraft",
    "genreId":5,
    "price":19.99,
    "releaseDate":"2011-11-18"
}

###
PUT http://localhost:5068/games/1
Content-Type: application/json

{
    "name": "Street Fighter II Turbo",
    "genreId": "1",
    "price": 89.99,
    "releaseDate": "1992-07-15"
}

###
DELETE http://localhost:5068/games/2
